# Use root/example as user/password credentials
version: '3.1'

services:

  mongos:
    container_name: mongos
    image: mongo:4.4.6
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: ECACHAIN
    ports:
      - "27017:27017"
 
  eca_chain_server:
    container_name: eca-chain
    image: dipaz/eca-chain-server:v1
    environment:
      # Use your IP Address
      MONGO_URI_1: mongodb://root:example@192.168.0.102:27017/admin
    ports:
      - "3000:3000"
