# Use root/example as user/password credentials
version: '3.1'

services:

  mongo_node_1:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: ECACHAIN
    ports:
      - "27017:27017"

  mongo_node_2:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: ECACHAIN
    ports:
      - "27018:27017"

  mongo_node_3:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: ECACHAIN
    ports:
      - "27019:27017"

  redis:
    image: "redis:alpine"
    command: redis-server --requirepass 1234admin
    ports:
      - "6379:6379"
 
 